### PR TITLE
Added shortcut: Send invite ⌘N

### PR DESCRIPTION
**Pull request by vematejo**
Created shortcut for sending Invite in main menu ⌘N

### CODE REVIEW

**Comment by aaronraimist** [comment]
Not a problem 😀

Thank you for working on these shortcuts!

**Comment by vematejo** [comment]
Podfile.lock added

**Comment by neilalexander** [comment]
I'm curious about the `wantsLayer="YES"` in some of the objects here. I am pretty sure this happened in someone else's PR too. It's strange, I wonder if Xcode is doing it automatically.

**Comment by vematejo** [comment]
Yes, Xcode made it automatically. :)

**Comment by vematejo** [comment]
OK, but ⌘J is already reserved for Edit - Find - Jump to Selection

**Comment by vematejo** [comment]
Maybe we can change it to alt+S : ⌥S   or alt+I : ⌥I . What do you think?

**Comment by neilalexander** [comment]
Either ⌘-Shift-I or ⌥I seems reasonable enough to me - perhaps ⌘-Shift-I might be better.

**Comment by aaronraimist** [comment]
Closing this since #94 got merged.

**Pull request closed without merging**
