### PR TITLE
Add version info to about screen

### PR DESCRIPTION
**Pull request by aaronraimist**
Build this change on your own computer and make sure it shows 56feccc. I think maybe if you open the about screen too fast after compiling it will either be blank or show the previous commit. Not sure what I need to do to fix that. Should this be in viewWillAppear or something?

Also this relies on you having set a git tag like "v0.0.1" to set the version

### CODE REVIEW

**Comment by neilalexander** [comment]
It looks like it shows the commit properly - it shows `Version c76e8be408197d1d60605552516ada17b7542754 (138)` - but may need to look into the fact that it overflows the text area. A short commit tag is probably acceptable!

I think either `viewDidLoad` or `viewWillAppear` is acceptable, I guess the latter happens at a later stage of the window drawing process.

screen shot 2018-08-14 at 22 23 31

**Comment by aaronraimist** [comment]
Oh yeah all you need to do is add a git tag called something like `v0.0.0` or `v0.0.1` and it will work properly

**Comment by neilalexander** [comment]
I'll give it a closer look tomorrow.

What might be interesting eventually is to look at versioning like [this script](https://github.com/yggdrasil-network/yggdrasil-go/blob/master/contrib/semver/version.sh) I wrote for another project, where v0.1.2-0003 derives 0.1 from the last v0.1 tag and 2 is derived from the merge commit count into `master` and the 0003 bit is derived from total commit count on the branch or so.

(That script largely assumes that the `master` branch is protected and that all merges to bump up the version will be through pull requests, but I guess it could be adapted.)

**Comment by neilalexander** [comment]
Indeed - I am cautious about assigning a version number at all (and giving the illusion of stability) until the major crashes are fixed.

**Comment by neilalexander** [comment]
Yikes, what happened here?

**Comment by aaronraimist** [comment]
No idea what I did. I'll open a new PR.

**Pull request closed without merging**
