### PR TITLE
Expand input field (#45)

### PR DESCRIPTION
**Pull request by aaronraimist**
So... this works pretty well but it is based on some code in a GitHub gist and StackOverflow answer without any license. I'm sure they are fine with people using it but I added a comment asking if they would explicitly license it. Not sure if you are comfortable merging this without that.

https://gist.github.com/entotsu/ddc136832a87a0fd2f9a0a6d4cf754ea

Only bug is, it doesn't shrink back down until you type the first letter. I'm sure that is a simple fix but I'm just not seeing it.

### CODE REVIEW

**Comment by aaronraimist** [comment]
Oh and it breaks controlTextDidChange (why?) and therefore typing notifications which I was in the process of trying to fix for #8

**Comment by neilalexander** [comment]
Are typing notifications still broken on this PR?

**Comment by aaronraimist** [comment]
Yes. Not sure why.

I haven't had time looked at this PR since I created it.

**Comment by neilalexander** [comment]
No problem - I can take a look shortly :-)

**Comment by aaronraimist** [comment]
It might be worth writing some tests to make sure things are working. I wouldn't have even noticed typing notifications broke here except I was going to try to fix those too.
    	
    	

    	Aaron Raimist
    
  




On Sun, Sep 23, 2018 at 1:32 PM -0500, "Neil Alexander" <notifications@github.com> wrote:












No problem - I can take a look shortly :-)

**Pull request merged**
