### PR TITLE
Only attempt to show resend message dialog when a message failed to send

### PR DESCRIPTION
**Pull request by pixlwave**
Fixes a crash that occurred when clicking the padlock icon.

### CODE REVIEW

**Comment by pixlwave** [comment]
Oh, should mention: Please test with a failed message before merging as I wasn't sure how to do this.

**Comment by neilalexander** [comment]
A better approach that is less impacting might be something like this in `MainViewRoomController.swift` line 203:
```
            let messageSendErrorHandler = { (roomId, eventId, userId) in
                if roomId == nil || eventId == nil {
                    return
                }
                if (MatrixServices.inst.eventCache[roomId!]?.contains(where: { $0.eventId == eventId && $0.sentState == MXEventSentStateFailed }))! {
                    let sheet = self.storyboard?.instantiateController(withIdentifier: NSStoryboard.SceneIdentifier("MessageSendFailedSheet")) as! MainViewSendErrorController
                    sheet.roomId = roomId!
                    sheet.eventId = eventId!
                    self.presentViewControllerAsSheet(sheet)
                }
            } as (_: String?, _: String?, _: String?) -> ()
```

**Comment by pixlwave** [comment]
Sure I can update. I was wondering though if it makes sense to be setting this handler for all messages even if they didn't fail sending?

**Comment by pixlwave** [comment]
Well that commit is very much more impacting, but I think that's how I'd do it. No offence if you'd rather not do that though 🙃

**Comment by pixlwave** [comment]
Thinking about it, creating the protocol might be a tad ott. I'd skip that part and just make the delegate type the controller.

**Pull request closed without merging**
